GET http://localhost:3001/user-api/users
###
POST http://localhost:3001/user-api/user
Content-Type: application/json

{
    "id" : 401,
    "name" : "Manish",
    "age" : 20
}

###
PUT http://localhost:3001/user-api/users/id
Content-Type: application/json

{
    "id" : 401,
    "name" : "Manish",
    "age" : 20
}

### 
GET http://localhost:3001/user-api/users/401

###
DELETE http://localhost:3001/user-api/users/402
###

GET http://localhost:3001/product-api/products
###
POST http://localhost:3001/product-api/products
Content-Type: application/json

{
    "productId" : 400,
    "name" : "Watch",
    "price" : 5000,
    "brand" : "rolex"
}

###
PUT http://localhost:3001/product-api/products/id
Content-Type: application/json

{
    "id" : 401,
    "name" : "Manish",
    "age" : 20
}

### 
GET http://localhost:3001/product-api/products/401

###
DELETE http://localhost:3001/product-api/products/402
